"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useAuth } from "@/contexts/AuthContext";
import type { DailyReport, OperationalRequest, ReportSections } from "@/lib/farm-reports";

const categories = ["purchase","feed","veterinary","repair","maintenance","equipment","staffing","emergency","other"] as const;
const groups = {
  farm1: {title:"Farm 1",fields:{pond1:"Pond 1",pond2:"Pond 2",pond3:"Pond 3",pond4:"Pond 4",water_issue:"Water issue"}},
  farm2: {title:"Farm 2",fields:{vat1:"Tarpaulin Vat 1",vat2:"Tarpaulin Vat 2",vat3:"Tarpaulin Vat 3",mortality:"Mortality",water_issue:"Water issue",pump_status:"Pump status"}},
  livestock: {title:"Livestock",fields:{goats:"Goats",ram:"Ram",cattle:"Cattle",piggery:"Piggery",poultry:"Poultry",mortality:"Mortality",sick_animals:"Sick animals",feed:"Feed",water:"Water"}},
  crops: {title:"Crops",fields:{report:"Crop report"}},
  people: {title:"People",fields:{workers_present:"Workers present",supervisor:"Supervisor",tasks_completed:"Tasks completed"}},
  problems: {title:"Problems",fields:{issues:"Issues",action_taken:"Action taken",request_category:"Request category"}},
};
const blankSections=():ReportSections=>({farm1:{pond1:"",pond2:"",pond3:"",pond4:"",water_issue:""},farm2:{vat1:"",vat2:"",vat3:"",mortality:"",water_issue:"",pump_status:""},livestock:{goats:"",ram:"",cattle:"",piggery:"",poultry:"",mortality:"",sick_animals:"",feed:"",water:""},crops:{report:""},people:{supervisor:"",tasks_completed:""},problems:{issues:"",action_taken:"",request_category:"other"}});
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Lagos",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const input="w-full min-h-11 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm disabled:bg-slate-50 disabled:text-slate-700";
const button="min-h-11 rounded-lg bg-emerald-700 px-4 py-2 font-medium text-white disabled:opacity-50";
const panel="rounded-xl border border-slate-200 bg-white p-4 sm:p-6 space-y-4";
type ReportForm={report_date:string;sections:ReportSections;decision_required:boolean};

function useOperations(kind:"daily-reports"|"operational-requests") {
  const [rows,setRows]=useState<(DailyReport|OperationalRequest)[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[page,setPage]=useState(1),[total,setTotal]=useState(0);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch(`/api/farm/${kind}?page=${page}`,{cache:"no-store"});const body=await response.json();if(!response.ok)throw Error(body.error||"Unable to load records");setRows(body.data??[]);setTotal(body.total??0);}catch(err){setError(err instanceof Error?err.message:"Unable to load records");}finally{setLoading(false);}},[kind,page]);
  useEffect(()=>{void load();},[load]);
  return {rows,loading,error,setError,load,page,setPage,total};
}

function useWrite(kind:string,onError:(message:string)=>void) {
  const {profile}=useAuth();
  const [busy,setBusy]=useState(false);
  const pending=useRef<{key:string;id:string}|null>(null);
  const lock=useRef(false);
  async function write(payload:unknown,id?:string){
    if(lock.current)return null;lock.current=true;setBusy(true);onError("");
    const key=JSON.stringify({id,payload});
    const storageKey=profile?`primefield-operation-retry:${profile.id}:${kind}`:null;
    if(!pending.current&&storageKey){try{pending.current=JSON.parse(sessionStorage.getItem(storageKey)||"null");}catch{/* Fresh key when browser storage is unavailable. */}}
    if(pending.current?.key!==key)pending.current={key,id:crypto.randomUUID()};
    if(storageKey){try{sessionStorage.setItem(storageKey,JSON.stringify(pending.current));}catch{/* Same-page retries remain protected. */}}
    try{const response=await fetch(`/api/farm/${kind}${id?`/${id}`:""}`,{method:id?"PUT":"POST",headers:{"Content-Type":"application/json","X-Request-ID":pending.current.id},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw Error(result.error||"Unable to save");pending.current=null;if(storageKey){try{sessionStorage.removeItem(storageKey);}catch{/* The operation is already saved. */}}return result.data;}catch(err){onError(err instanceof Error?err.message:"Unable to save. Retry when connected.");return null;}finally{lock.current=false;setBusy(false);}
  }
  return {write,busy};
}

export function FarmDailyReports({admin=false,historyOnly=false}:{admin?:boolean;historyOnly?:boolean}) {
  const {profile}=useAuth(),records=useOperations("daily-reports");
  const [form,setForm]=useState<ReportForm>({report_date:"",sections:blankSections(),decision_required:false}),[selected,setSelected]=useState<DailyReport|null>(null),[reason,setReason]=useState(""),[review,setReview]=useState(""),[message,setMessage]=useState(""),[restored,setRestored]=useState(false);
  const storageKey=profile?`primefield-report-draft:${profile.id}`:null;
  const {write,busy}=useWrite("daily-reports",records.setError);
  useEffect(()=>{if(!storageKey||admin||historyOnly)return;try{const saved=localStorage.getItem(storageKey);if(saved){const draft=JSON.parse(saved);setForm(draft.form);setSelected(draft.selected??null);setMessage("Local draft restored. Save it when connected.");}else setForm({report_date:today(),sections:blankSections(),decision_required:false});}catch{setForm({report_date:today(),sections:blankSections(),decision_required:false});}setRestored(true);},[storageKey,admin,historyOnly]);
  useEffect(()=>{if(!storageKey||!restored||admin||historyOnly||selected?.status==="submitted")return;try{localStorage.setItem(storageKey,JSON.stringify({form,selected}));}catch{/* Server saving remains available when device storage is full. */}},[form,selected,storageKey,restored,admin,historyOnly]);
  const readOnly=admin||historyOnly||selected?.status==="submitted";
  function choose(row:DailyReport){setSelected(row);setForm({report_date:row.report_date,sections:row.sections,decision_required:row.decision_required});setReason("");setReview(row.review_note??"");setMessage("");}
  function fresh(){setSelected(null);setForm({report_date:today(),sections:blankSections(),decision_required:false});setReason("");setMessage("");}
  async function save(submit:boolean){
    if(selected&&selected.status!=="draft")return;
    if(selected&&!reason.trim()){records.setError("Enter a reason for changing this draft.");return;}
    const row=await write(selected?{...form,operation:"update",revision:selected.revision,reason}:form,selected?.id) as DailyReport|null;
    if(!row)return;setSelected(row);setMessage("Draft saved.");
    if(submit){const submitted=await write({operation:"submit",revision:row.revision},row.id) as DailyReport|null;if(!submitted){setMessage("Submission could not be confirmed. Use Submit saved draft to retry, or reload records to check its status.");return;}setSelected(submitted);setMessage(form.decision_required?"Report submitted and operational request linked.":"Report submitted.");if(storageKey){try{localStorage.removeItem(storageKey);}catch{/* Submission is already stored online. */}}}
    await records.load();
  }
  async function submitSaved(){if(!selected)return;const row=await write({operation:"submit",revision:selected.revision},selected.id) as DailyReport|null;if(row){setSelected(row);setMessage("Report submitted. Any required decision is linked to an operational request.");if(storageKey){try{localStorage.removeItem(storageKey);}catch{/* Submission is already stored online. */}}await records.load();}}
  async function markReviewed(){if(!selected)return;const row=await write({operation:"review",revision:selected.revision,review_note:review,reason},selected.id) as DailyReport|null;if(row){choose(row);setMessage("Review saved.");await records.load();}}
  return <div className="mx-auto max-w-6xl space-y-6 text-slate-800">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">{admin?"Daily report review":historyOnly?"Daily report history":"Daily Report"}</h1><p className="mt-1 text-sm text-slate-600">{admin?"Review submitted Primefield reports and decisions.":"Record farm conditions, people and problems for the day."}</p></div>{!admin&&<Link className="text-sm font-semibold text-emerald-700 underline" href={historyOnly?"/daily-report":"/daily-report/history"}>{historyOnly?"Write a report":"View report history"}</Link>}</div>
    {records.error&&<div role="alert" className="rounded-lg bg-red-50 p-4 text-red-800">{records.error} <button className="underline" onClick={()=>void records.load()}>Reload records</button></div>}{message&&<p role="status" className="rounded-lg bg-emerald-50 p-4 text-emerald-800">{message}</p>}
    {(!historyOnly&&!admin||selected)&&<section className={panel}>
      <div className="flex flex-wrap justify-between gap-3"><h2 className="font-semibold">{selected?`${selected.report_date} · ${selected.status} · revision ${selected.revision}`:"New daily report"}</h2>{!admin&&!historyOnly&&<button className="text-emerald-700 underline disabled:opacity-50" disabled={busy} onClick={fresh}>New report</button>}</div>
      {selected?.reviewed_at&&<p className="text-sm text-emerald-800">Reviewed {new Date(selected.reviewed_at).toLocaleString()}: {selected.review_note}</p>}
      <label className="block text-sm font-medium">Report date<input type="date" required className={`${input} mt-1 max-w-xs`} disabled={!!readOnly||busy||!!selected} value={form.report_date} onChange={event=>setForm({...form,report_date:event.target.value})}/></label>
      <div className="grid gap-4 lg:grid-cols-2">{Object.entries(groups).map(([key,group])=><fieldset key={key} disabled={!!readOnly||busy} className="min-w-0 rounded-lg border border-slate-200 p-4"><legend className="px-1 font-semibold">{group.title}</legend><div className="grid gap-3 sm:grid-cols-2">{Object.entries(group.fields).map(([field,label])=>{const value=(form.sections[key as keyof ReportSections] as Record<string,string|number>)[field]??"";const update=(next:string)=>setForm({...form,sections:{...form.sections,[key]:{...form.sections[key as keyof ReportSections],[field]:field==="workers_present"?(next===""?undefined:Number(next)):next}}});return <label key={field} className="block text-sm font-medium">{label}{field==="request_category"?<select aria-label={label} className={`${input} mt-1`} value={value} onChange={event=>update(event.target.value)}>{categories.map(category=><option key={category}>{category}</option>)}</select>:field==="workers_present"?<input aria-label={label} type="number" inputMode="numeric" min={0} max={9999} step={1} className={`${input} mt-1`} value={value} onChange={event=>update(event.target.value)}/>:<textarea aria-label={label} rows={2} maxLength={2000} className={`${input} mt-1 resize-y`} value={value} onChange={event=>update(event.target.value)}/>}</label>;})}</div></fieldset>)}</div>
      <label className="flex min-h-11 items-center gap-3 text-sm font-medium"><input type="checkbox" disabled={!!readOnly||busy} checked={form.decision_required} onChange={event=>setForm({...form,decision_required:event.target.checked})}/>CEO decision required (creates a linked request on submission)</label>
      {!readOnly&&<><p className="text-xs text-slate-500">Drafts save on this device. Use Save draft to store online. Submitted reports are read only.</p>{selected&&<label className="block text-sm font-medium">Reason for draft changes<input maxLength={2000} className={`${input} mt-1`} value={reason} onChange={event=>setReason(event.target.value)}/></label>}<div className="flex flex-wrap gap-3"><button className={button} disabled={busy} onClick={()=>void save(false)}>Save draft</button><button className={button} disabled={busy} onClick={()=>void save(true)}>Save and submit</button>{selected&&<button className={button} disabled={busy} onClick={()=>void submitSaved()}>Submit saved draft</button>}</div></>}
      {admin&&selected?.status==="submitted"&&<div className="space-y-3 border-t pt-4"><label className="block text-sm font-medium">Review note<textarea aria-label="Review note" maxLength={2000} className={`${input} mt-1`} value={review} onChange={event=>setReview(event.target.value)}/></label><label className="block text-sm font-medium">Reason<input maxLength={2000} className={`${input} mt-1`} value={reason} onChange={event=>setReason(event.target.value)}/></label><button disabled={busy||!review.trim()||!reason.trim()} className={button} onClick={()=>void markReviewed()}>Record review</button><Link href="/dashboard/farm/operational-requests" className="ml-3 text-emerald-700 underline">Review operational requests</Link></div>}
    </section>}
    <section className={panel}><h2 className="font-semibold">{admin?"Farm reports":"Your reports"}</h2>{records.loading?<p role="status">Loading reports…</p>:!records.rows.length?<p className="text-sm text-slate-500">No daily reports recorded.</p>:<div className="space-y-2">{(records.rows as DailyReport[]).map(row=><button key={row.id} disabled={busy} className="flex min-h-14 w-full flex-wrap items-center justify-between gap-2 rounded-lg border p-3 text-left hover:bg-emerald-50" onClick={()=>choose(row)}><span>{row.report_date}<span className="ml-2 text-sm text-slate-500">{row.status} · revision {row.revision}</span></span><span className="text-sm">{row.reviewed_at?"Reviewed":row.decision_required?"Decision required":"View report"}</span></button>)}</div>}<Pagination {...records}/></section>
  </div>;
}

function Pagination({page,setPage,total,loading}:{page:number;setPage:(page:number)=>void;total:number;loading:boolean}){return <div className="flex flex-wrap items-center justify-between gap-3 text-sm"><span>{total} records · page {page}</span><div className="flex gap-2"><button className="min-h-11 rounded border px-3 disabled:opacity-40" disabled={loading||page===1} onClick={()=>setPage(page-1)}>Previous</button><button className="min-h-11 rounded border px-3 disabled:opacity-40" disabled={loading||page*50>=total} onClick={()=>setPage(page+1)}>Next</button></div></div>;}

export function FarmOperationalRequests({admin=false}:{admin?:boolean}) {
  const {profile}=useAuth();
  const records=useOperations("operational-requests"),{write,busy}=useWrite("operational-requests",records.setError);
  const [date,setDate]=useState(""),[category,setCategory]=useState("other"),[description,setDescription]=useState(""),[selected,setSelected]=useState<OperationalRequest|null>(null),[reason,setReason]=useState(""),[response,setResponse]=useState(""),[resolution,setResolution]=useState(""),[message,setMessage]=useState("");
  const [restored,setRestored]=useState(false);
  const draftKey=profile?`primefield-request-draft:${profile.id}`:null;
  useEffect(()=>{if(admin||!draftKey)return;try{const saved=JSON.parse(localStorage.getItem(draftKey)||"null");if(saved){setDate(saved.date||today());setCategory(saved.category||"other");setDescription(saved.description||"");}else setDate(today());}catch{setDate(today());}setRestored(true);},[admin,draftKey]);
  useEffect(()=>{if(admin||!draftKey||!restored)return;try{localStorage.setItem(draftKey,JSON.stringify({date,category,description}));}catch{/* Online submission remains available. */}},[admin,draftKey,restored,date,category,description]);
  async function create(){const row=await write({request_date:date,category,description});if(row){setDescription("");setMessage("Operational request submitted.");await records.load();}}
  async function decide(operation:string){if(!selected)return;const row=await write({operation,revision:selected.revision,reason,...(operation==="resolve"?{resolution,...(response.trim()?{ceo_response:response}:{})}:{ceo_response:response})},selected.id) as OperationalRequest|null;if(row){setSelected(row);setMessage("Request updated.");setReason("");await records.load();}}
  function choose(row:OperationalRequest){setSelected(row);setResponse(row.ceo_response??"");setResolution(row.resolution??"");setReason("");setMessage("");}
  return <div className="mx-auto max-w-5xl space-y-6 text-slate-800"><div><h1 className="text-2xl font-bold">Operational Requests</h1><p className="mt-1 text-sm text-slate-600">{admin?"Respond to farm needs, approve resources and record resolution.":"Request resources or action and follow the CEO response."}</p></div>
    {records.error&&<div role="alert" className="rounded-lg bg-red-50 p-4 text-red-800">{records.error} <button className="underline" onClick={()=>void records.load()}>Reload records</button></div>}{message&&<p role="status" className="rounded-lg bg-emerald-50 p-4 text-emerald-800">{message}</p>}
    {!admin&&<form className={panel} onSubmit={event=>{event.preventDefault();void create();}}><h2 className="font-semibold">New request</h2><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Request date<input disabled={busy} required type="date" className={`${input} mt-1`} value={date} onChange={event=>setDate(event.target.value)}/></label><label className="text-sm font-medium">Category<select aria-label="Category" disabled={busy} className={`${input} mt-1`} value={category} onChange={event=>setCategory(event.target.value)}>{categories.map(value=><option key={value}>{value}</option>)}</select></label></div><label className="block text-sm font-medium">What do you need?<textarea disabled={busy} aria-label="What do you need?" required maxLength={2000} rows={4} className={`${input} mt-1`} value={description} onChange={event=>setDescription(event.target.value)}/></label><button className={button} disabled={busy||!description.trim()}>Submit request</button></form>}
    {selected&&<section className={panel}><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">{selected.request_date} · {selected.category}</h2><span className="text-sm">{selected.status} · revision {selected.revision}</span></div><p className="whitespace-pre-wrap break-words">{selected.description}</p>{selected.report_id&&<p className="break-all text-xs text-slate-500">Linked daily report: {selected.report_id}</p>}<p className="whitespace-pre-wrap break-words text-sm"><strong>CEO response:</strong> {selected.ceo_response||"Awaiting response"}</p>{selected.resolution&&<p className="whitespace-pre-wrap break-words text-sm"><strong>Resolution:</strong> {selected.resolution}</p>}{admin&&["pending","approved"].includes(selected.status)&&<div className="space-y-3 border-t pt-4"><label className="block text-sm font-medium">CEO response<textarea aria-label="CEO response" maxLength={2000} className={`${input} mt-1`} value={response} onChange={event=>setResponse(event.target.value)}/></label><label className="block text-sm font-medium">Reason<input maxLength={2000} className={`${input} mt-1`} value={reason} onChange={event=>setReason(event.target.value)}/></label><div className="flex flex-wrap gap-3"><button className={button} disabled={busy||!reason.trim()||!response.trim()} onClick={()=>void decide("respond")}>Send response</button>{selected.status==="pending"&&<><button className={button} disabled={busy||!reason.trim()||!response.trim()} onClick={()=>void decide("approve")}>Approve</button><button className="min-h-11 rounded-lg border border-red-300 px-4 text-red-700 disabled:opacity-50" disabled={busy||!reason.trim()||!response.trim()} onClick={()=>void decide("decline")}>Decline</button></>}</div>{selected.status==="approved"&&<><label className="block text-sm font-medium">Resolution<textarea aria-label="Resolution" maxLength={2000} className={`${input} mt-1`} value={resolution} onChange={event=>setResolution(event.target.value)}/></label><button className={button} disabled={busy||!reason.trim()||!resolution.trim()||!response.trim()} onClick={()=>void decide("resolve")}>Mark resolved</button></>}</div>}</section>}
    <section className={panel}><h2 className="font-semibold">{admin?"Farm request history":"Your request history"}</h2>{records.loading?<p role="status">Loading requests…</p>:!records.rows.length?<p className="text-sm text-slate-500">No operational requests recorded.</p>:<div className="space-y-2">{(records.rows as OperationalRequest[]).map(row=><button key={row.id} disabled={busy} className="min-h-16 w-full rounded-lg border p-3 text-left hover:bg-emerald-50" onClick={()=>choose(row)}><span className="flex flex-wrap justify-between gap-2 text-sm font-semibold"><span>{row.request_date} · {row.category}</span><span>{row.status}</span></span><span className="mt-1 block truncate text-sm text-slate-600">{row.description}</span></button>)}</div>}<Pagination {...records}/></section>
  </div>;
}
