"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import Link from "next/link";
import {useAuth} from "@/contexts/AuthContext";
type Stock={id:string;feed_type:string;feed_source:string;current_bags:number|null;initialized_at:string|null;revision:number};
type Movement={id:string;bags_delta:number;movement_date:string;created_at:string;actor_id:string;reason:string|null;daily_feed_id:string|null;purchase_id:string|null};
const types=["fish","goat","chicken","pig","turkey","cattle","other"];
const input="min-h-11 w-full rounded-lg border border-slate-300 p-3 text-sm";
export function FeedStock({admin=false}:{admin?:boolean}){
 const {profile}=useAuth();const [stocks,setStocks]=useState<Stock[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[selected,setSelected]=useState<Stock|null>(null),[history,setHistory]=useState<Movement[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[type,setType]=useState("fish"),[source,setSource]=useState("local"),[quantity,setQuantity]=useState(""),[reason,setReason]=useState(""),[date,setDate]=useState("");
 const pending=useRef<{id:string;body:Record<string,unknown>}|null>(null),lock=useRef(false);const key=profile?`primefield-feed-stock-retry:${profile.id}`:null;
 useEffect(()=>{setDate(new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Lagos",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()));if(!key)return;try{pending.current=JSON.parse(localStorage.getItem(key)||"null");setUncertain(!!pending.current);}catch{setError("Saved entry could not be read. Check history before submitting.");setUncertain(true);}},[key]);
 const load=useCallback(async()=>{setLoading(true);try{const response=await fetch("/api/farm/feed-stock",{cache:"no-store"});const result=await response.json();if(!response.ok)throw Error(result.error||"Unable to load feed stock");setStocks(result.data??[]);}catch(err){setError(err instanceof Error?err.message:"Unable to load feed stock");}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{if(!selected)return;setHistory([]);void (async()=>{try{const response=await fetch(`/api/farm/feed-stock?history=1&stock_id=${selected.id}&page=${page}&limit=100`,{cache:"no-store"});const result=await response.json();if(!response.ok)throw Error(result.error||"Unable to load movement history");setHistory(result.data??[]);setTotal(result.total??0);}catch(err){setError(err instanceof Error?err.message:"Unable to load movement history");}})();},[selected,page]);
 useEffect(()=>{if(!pending.current)return;const body=pending.current.body,payload=body.payload as Record<string,unknown>;const record=stocks.find(row=>row.id===body.id);setType(String(payload.feed_type??record?.feed_type??"fish"));setSource(String(payload.feed_source??record?.feed_source??"local"));setDate(String(payload.date??""));setQuantity(String(payload.bags_available??payload.bags_delta??""));setReason(String(body.reason??""));},[stocks]);
 const current=stocks.find(row=>row.feed_type===type&&row.feed_source===source);
 async function save(){if(lock.current)return;if(!key)return setError("Sign in before recording stock.");const hadPending=!!pending.current;if(!pending.current){const number=Number(quantity);if(!quantity||!Number.isInteger(number)||(current?.initialized_at?number===0:number<0)||!reason.trim())return setError("Enter a whole bag count and a reason. Adjustments may be positive or negative.");pending.current={id:crypto.randomUUID(),body:{operation:current?.initialized_at?"adjust":"opening",...(current?.initialized_at?{id:current.id}:{}),reason,payload:{date,...(current?.initialized_at?{bags_delta:number,expected_revision:current.revision}:{feed_type:type,feed_source:source,bags_available:number})}}};}lock.current=true;setBusy(true);setError("");try{localStorage.setItem(key,JSON.stringify(pending.current));}catch{setError("Device storage is unavailable. The entry was not sent.");if(!hadPending)pending.current=null;setBusy(false);lock.current=false;return;}setUncertain(true);try{const response=await fetch("/api/farm/feed-stock",{method:"POST",headers:{"Content-Type":"application/json","X-Request-ID":pending.current.id},body:JSON.stringify(pending.current.body)});const result=await response.json();if(!response.ok){if([400,409].includes(response.status)){pending.current=null;localStorage.removeItem(key);setUncertain(false);}throw Error(result.error||"Unable to confirm stock entry");}pending.current=null;localStorage.removeItem(key);setUncertain(false);setQuantity("");setReason("");setSelected(null);await load();}catch(err){setError(err instanceof Error?err.message:"Unconfirmed stock entry. Retry saved values.");}finally{setBusy(false);lock.current=false;}}
 return <div className="mx-auto max-w-5xl space-y-5 text-slate-800"><h1 className="text-2xl font-bold">Feed Inventory</h1><p className="text-sm text-slate-600">Whole unopened bags available, by feed type and source. Historical records are preserved; opening stock requires a real physical count.</p>{error&&<div role="alert" className="rounded bg-red-50 p-4 text-red-800">{error}</div>}{uncertain&&<p role="status" className="rounded bg-amber-50 p-4">Saved stock change is unconfirmed. Its values stay locked until the same entry succeeds.</p>}{loading?<p role="status">Loading feed stock...</p>:<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{types.flatMap(feedType=>["local","foreign"].map(feedSource=>{const stock=stocks.find(row=>row.feed_type===feedType&&row.feed_source===feedSource);return <article key={`${feedType}:${feedSource}`} className="rounded-xl border bg-white p-4"><h2 className="font-semibold capitalize">{feedType} - {feedSource}</h2><p className="mt-2 text-xl font-bold">{stock?.initialized_at&&stock.current_bags!==null?`${stock.current_bags} bags remaining`:"Awaiting physical opening count"}</p>{stock&&<button className="mt-2 min-h-11 text-sm text-emerald-700 underline" onClick={()=>{setSelected(stock);setPage(1);}}>View history</button>}</article>;}))}</div>}
 {!admin&&<p className="rounded-xl bg-blue-50 p-4 text-sm">Bimbo records opening counts and corrections. <Link href="/daily-feed" className="font-semibold text-emerald-700 underline">Record new bags opened in Daily Feed</Link>. <Link href="/expenses/feed" className="font-semibold text-emerald-700 underline">Record purchased feed</Link>; future receipts link automatically.</p>}
 {admin&&<section className="space-y-4 rounded-xl border bg-white p-4"><h2 className="font-semibold">Opening physical count / signed adjustment</h2><fieldset disabled={busy||uncertain} className="grid gap-4 sm:grid-cols-2"><label>Feed type<select className={input} value={type} onChange={event=>setType(event.target.value)}>{types.map(value=><option key={value}>{value}</option>)}</select></label><label>Source<select className={input} value={source} onChange={event=>setSource(event.target.value)}><option>local</option><option>foreign</option></select></label><label>Date<input className={input} type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><label>{current?.initialized_at?"Signed bag adjustment (+ / -)":"Actual unopened bags counted"}<input className={input} type="number" step={1} min={current?.initialized_at?undefined:0} value={quantity} onChange={event=>setQuantity(event.target.value)}/></label><label className="sm:col-span-2">Reason<input className={input} maxLength={2000} value={reason} onChange={event=>setReason(event.target.value)}/></label></fieldset><p className="text-sm text-slate-600">Opening establishes authority. Adjustments append movements and preserve history.</p><button className="min-h-11 rounded-lg bg-emerald-700 px-4 text-white disabled:opacity-50" disabled={busy} onClick={()=>void save()}>{busy?"Saving...":uncertain?"Retry saved stock change":"Save stock movement"}</button></section>}
 {selected&&<section className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-semibold capitalize">{selected.feed_type} - {selected.feed_source} history</h2>{!history.length?<p className="text-sm text-slate-500">No movements on this page.</p>:history.map(row=><article className="space-y-1 rounded-lg border p-3 text-sm" key={row.id}><p className="font-semibold">{row.bags_delta>0?"+":""}{row.bags_delta} bags</p><p>{row.movement_date} - {row.created_at}</p><p className="break-all">Actor: {row.actor_id||"Unknown"}</p>{row.reason&&<p>{row.reason}</p>}{row.daily_feed_id&&<p className="break-all">Daily feed source: {row.daily_feed_id}</p>}{row.purchase_id&&<p className="break-all">Purchase source: {row.purchase_id}</p>}</article>)}<div className="flex gap-3"><button className="min-h-11 rounded border px-3" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><button className="min-h-11 rounded border px-3" disabled={page*100>=total} onClick={()=>setPage(page+1)}>Next</button></div></section>}
 </div>;
}
