"use client";
import { useEffect, useRef, useState, type ReactNode } from "react";
import Link from "next/link";
import { ArrowUpRight, RefreshCw, Tractor, Building2, Sparkles, Radio, ChevronRight, ClipboardList, CircleCheck, Plus, CalendarDays } from "lucide-react";
import type { getCeoOverview } from "@/lib/ceo-overview";
import { farmDateToday, farmProductLabel } from "@/lib/farm-products";

type Overview = Awaited<ReturnType<typeof getCeoOverview>>;
const number = (value: unknown) => Number(value).toLocaleString();
const money = (value: number, currency = "NGN") => new Intl.NumberFormat("en", { style: "currency", currency, minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value);
const label = (value: unknown) => String(value ?? "Unknown").replaceAll("_", " ");
const panel = "rounded-2xl border border-slate-200/80 bg-white shadow-[0_3px_20px_-12px_rgba(15,23,42,0.18)]";
const linkStyle = "inline-flex min-h-11 min-w-11 items-center gap-1.5 text-xs font-semibold text-teal-700 hover:text-teal-900 focus-visible:outline focus-visible:outline-2 focus-visible:outline-teal-600 focus-visible:outline-offset-4";
function Zone({ name, subtitle, href, icon, children }: { name: string; subtitle: string; href: string; icon: ReactNode; children: ReactNode }) {
  return <section className={`${panel} p-5 sm:p-6 min-w-0`} aria-label={name}><div className="flex items-start justify-between gap-3 mb-5"><div className="flex gap-3 items-center"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-teal-50 text-teal-700">{icon}</span><div><h2 className="font-heading text-sm font-bold tracking-wide text-slate-900">{name}</h2><p className="text-xs text-slate-500 mt-1">{subtitle}</p></div></div><Link className={linkStyle} href={href} aria-label={`Open ${name}`}><ArrowUpRight className="h-4 w-4" /></Link></div>{children}</section>;
}
function Metric({ title, value, note }: { title: string; value: ReactNode; note?: string }) {
  return <div className="min-w-0"><p className="text-xs text-slate-500">{title}</p><p className="font-heading text-xl sm:text-2xl font-bold tracking-tight mt-2 text-slate-900 break-words">{value}</p>{note && <p className="text-[11px] text-slate-500 mt-1 leading-relaxed">{note}</p>}</div>;
}
function Unavailable({ error }: { error: string }) { return <p role="alert" className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900 leading-relaxed">{error}</p>; }
function Empty({ children }: { children: ReactNode }) { return <p className="text-sm text-slate-500 py-3 leading-relaxed">{children}</p>; }
function Distribution({ title, rows }: { title: string; rows: { name: string; count: number }[] }) {
  const total = rows.reduce((sum, row) => sum + row.count, 0);
  return <div><h3 className="text-xs font-semibold mb-3">{title}</h3>{total ? <ul className="space-y-3">{rows.map(row => <li key={row.name}><div className="flex justify-between text-xs mb-1.5"><span className="capitalize text-slate-500">{label(row.name)}</span><strong>{number(row.count)}</strong></div><div className="h-1.5 bg-slate-100 rounded-full overflow-hidden" aria-hidden="true"><div className="h-full bg-teal-500 rounded-full" style={{ width: `${row.count / total * 100}%` }} /></div></li>)}</ul> : <Empty>No leads in this period.</Empty>}</div>;
}

export function CeoDashboard() {
  const today = farmDateToday();
  const [from, setFrom] = useState(today.slice(0, 8) + "01"), [to, setTo] = useState(today);
  const [data, setData] = useState<Overview | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const controller = useRef<AbortController | null>(null);
  async function load(start = from, end = to) {
    controller.current?.abort(); const active = new AbortController(); controller.current = active;
    setLoading(true); setError("");
    try {
      if (!start || !end || start > end) throw new Error("Choose a valid date range.");
      const response = await fetch(`/api/ceo/overview?from=${start}&to=${end}`, { cache: "no-store", signal: active.signal });
      const result = await response.json();
      if (!response.ok) throw new Error(result.error || "Dashboard data could not be loaded.");
      if (!active.signal.aborted) setData(result);
    } catch (fault) { if (!active.signal.aborted) { setData(null); setError(fault instanceof Error ? fault.message : "Dashboard data could not be loaded."); } }
    finally { if (!active.signal.aborted) setLoading(false); }
  }
  useEffect(() => { void load(); return () => controller.current?.abort(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const farm = data?.farm.data, content = data?.content.data, property = data?.properties.data, crm = data?.crm.data;
  const pending = data?.operations.data?.pending ?? [];
  return <div className="min-h-full bg-[#f5f7fa] text-slate-900 pb-8">
    <header className="px-4 sm:px-6 lg:px-8 pt-5 pb-4 border-b border-slate-200/70"><div className="flex flex-wrap items-center justify-between gap-4"><div className="pl-12 lg:pl-0"><p className="text-[10px] font-semibold tracking-[0.18em] uppercase text-teal-700 mb-1">BossBimbz · Business overview</p><h1 className="font-heading font-bold text-2xl tracking-tight">CEO Dashboard</h1></div><button onClick={() => void load()} disabled={loading} className="flex min-h-11 gap-2 items-center text-sm font-medium px-3 py-2 rounded-xl border border-slate-200 bg-white hover:bg-teal-50 disabled:opacity-50" aria-label="Refresh dashboard"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />Refresh</button></div></header>
    <div className="p-4 sm:p-6 lg:p-8 max-w-[1680px] mx-auto"><div className="flex flex-wrap items-end justify-between gap-4 mb-6"><div><h2 className="font-heading text-lg font-semibold">Your businesses, at a glance.</h2><p className="text-sm text-slate-500 mt-1">Performance, operations and decisions in one place.</p></div><form className="flex items-end flex-wrap gap-2" onSubmit={event => { event.preventDefault(); void load(); }}><label className="text-[11px] text-slate-500">From<input aria-label="Period start" type="date" required value={from} onChange={event => setFrom(event.target.value)} className="block mt-1 rounded-lg border border-slate-200 bg-white p-2 text-xs text-slate-700 max-w-[145px] min-h-11" /></label><label className="text-[11px] text-slate-500">To<input aria-label="Period end" type="date" required value={to} onChange={event => setTo(event.target.value)} className="block mt-1 rounded-lg border border-slate-200 bg-white p-2 text-xs text-slate-700 max-w-[145px] min-h-11" /></label><button className="rounded-lg bg-teal-700 text-white px-3 py-2 text-xs font-semibold hover:bg-teal-800 disabled:opacity-50 min-h-11" disabled={loading}>Apply</button></form></div>
      {error && <Unavailable error={error} />}
      {loading ? <div role="status" aria-label="Loading dashboard" className="grid lg:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)] gap-6"><div className={`${panel} h-96 animate-pulse`} /><div className={`${panel} h-64 animate-pulse`} /><span className="sr-only">Loading dashboard…</span></div> : data && <>
      <p className="text-[11px] text-slate-500 mb-4">Reporting period: {data.scope.from} — {data.scope.to} · Updated {new Date(data.generatedAt).toLocaleTimeString("en", { hour: "2-digit", minute: "2-digit" })}</p>
      <div className="grid xl:grid-cols-[minmax(0,2fr)_minmax(280px,0.9fr)] gap-6 items-start"><div className="space-y-6 min-w-0">
        <Zone name="PRIMEFIELD" subtitle="Farm performance & current stock" href="/dashboard/farm" icon={<Tractor className="h-5 w-5" />}>
          {data.farm.error ? <Unavailable error={data.farm.error} /> : farm && <>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-y-6 gap-x-4 pb-6 border-b border-slate-100"><Metric title="Revenue" value={money(farm.finance.revenue)} /><Metric title="Expenses" value={money(farm.finance.total_expenses)} note="General expenses + feed, counted once" /><Metric title="Operational net" value={money(farm.finance.operational_net)} /></div>
            <div className="grid sm:grid-cols-2 gap-3 my-5"><div className="rounded-xl bg-teal-50 p-4"><Metric title="Owner funds balance" value={money(farm.finance.closing_balance)} note={`As at ${data.scope.to}`} /></div><div className="rounded-xl bg-slate-50 p-4"><Metric title="Sales cash balance" value={money(farm.finance.sales_cash_balance)} note={`As at ${data.scope.to}`} /></div></div>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 mb-5"><Metric title="Fish stock" value={number(farm.fish.reduce((sum, row) => sum + Number(row.current_stock), 0))} note="Current inventory · fish" /><Metric title="Livestock count" value={number(farm.livestock.reduce((sum, row) => sum + Number(row.current_stock), 0))} note="Current inventory · animals" /><Metric title="Sales recorded" value={number(farm.salesCount)} note="Active sales in period" /><Metric title="Mortality" value={number(farm.mortality.reduce((sum,row)=>sum+Number(row.quantity),0))} note="Active mortality in period" /></div>
            <section aria-label="Feed inventory" className="mb-5 rounded-xl bg-teal-50/50 p-4"><h3 className="text-sm font-semibold mb-2">Feed Inventory</h3>{farm.feedError?<Unavailable error={farm.feedError}/>:farm.feed?.length?<div className="grid gap-2 sm:grid-cols-2">{farm.feed.map(row=><p className="flex flex-wrap justify-between gap-2 text-xs py-2 border-b border-teal-100" key={String(row.id)}><span className="capitalize">{row.feed_type==="fish"?"Fish":farmProductLabel(String(row.feed_type))} · {String(row.feed_source)}</span><strong>{row.initialized_at&&row.current_bags!=null?`${number(row.current_bags)} bags`:"Opening count required"}</strong></p>)}</div>:<Empty>No feed types recorded. A real opening count is required before bags can be reported.</Empty>}<Link className={linkStyle} href="/dashboard/farm/feed-stock">View feed stock & history <ArrowUpRight className="h-3.5 w-3.5"/></Link></section><details className="border-t border-slate-100 pt-4"><summary className="cursor-pointer text-xs font-semibold text-slate-700">Stock & mortality detail</summary><div className="grid sm:grid-cols-2 gap-5 mt-4 text-xs"><div><h3 className="font-semibold mb-2">Current stock by type</h3>{farm.inventory.length ? farm.inventory.map(row => <p className="flex justify-between gap-3 py-1.5 border-b border-slate-100" key={String(row.id)}><span>{farmProductLabel(String(row.product))}</span><strong>{number(row.current_stock)}</strong></p>) : <Empty>No inventory recorded.</Empty>}</div><div><h3 className="font-semibold mt-4 mb-2">Mortality in period</h3>{farm.mortality.length ? farm.mortality.map(row => <p key={row.product} className="flex justify-between py-1.5"><span>{farmProductLabel(row.product)}</span><strong>{number(row.quantity)}</strong></p>) : <Empty>No active mortality records in this period.</Empty>}</div></div></details>

          </>}
        </Zone>
        <div className="grid md:grid-cols-2 gap-6">
          <Zone name="BOSSBIMZ" subtitle="Content & audience performance" href="/content" icon={<Radio className="h-5 w-5" />}>
            {data.content.error ? <Unavailable error={data.content.error} /> : content && <><div className="grid grid-cols-2 gap-4 mb-5"><Metric title="Content published" value={number(content.published)} /><Metric title="Leads" value={number(content.leads)} /></div><div className="space-y-3">{content.accounts.length ? content.accounts.map(row => <div key={`${row.platform}:${row.account_id ?? ""}`} className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-semibold capitalize">{label(row.platform)}</p><div className="grid grid-cols-2 gap-3 mt-2"><p className="text-xs text-slate-500">Followers <strong className="block mt-1 text-base text-slate-900">{row.followers == null ? "Unavailable" : number(row.followers)}</strong></p><p className="text-xs text-slate-500">Reach <strong className="block mt-1 text-base text-slate-900">{row.reach == null ? "Unavailable" : number(row.reach)}</strong></p></div><p className="text-[10px] text-slate-500 mt-2">Snapshot: {String(row.metric_date)} · {label(row.source)}</p></div>) : <Empty>No audience snapshots recorded. Add an account observation in Content Manager.</Empty>}</div><div className="mt-4 pt-3 border-t border-slate-100">{content.sales.length ? content.sales.map(row => <div key={row.currency} className="text-xs space-y-2 mb-3"><p className="flex justify-between gap-2"><span>Mentorship sales</span><strong>{money(row.mentorship, row.currency)}</strong></p><p className="flex justify-between gap-2"><span>Affiliate sales</span><strong>{money(row.affiliate, row.currency)}</strong></p></div>) : <Empty>No mentorship or affiliate sales in this period.</Empty>}</div></>}
          </Zone>
          <Zone name="PROPERTIES" subtitle="Rental portfolio & maintenance" href="/property" icon={<Building2 className="h-5 w-5" />}>
            {data.properties.error ? <Unavailable error={data.properties.error} /> : property && <><div className="grid grid-cols-2 gap-x-4 gap-y-5"><Metric title="Active properties" value={number(property.properties)} /><Metric title="Vacancies" value={number(property.vacancies)} note={`${number(property.units)} units currently recorded`} /><Metric title="Open maintenance" value={number(property.openMaintenance)} /><Metric title="Open repairs" value={number(property.openRepairs)} /></div><div className="mt-5 pt-4 border-t border-slate-100">{property.finances.length ? property.finances.map(row => <div className="text-xs space-y-2 mb-4" key={row.currency}><p className="flex justify-between gap-2"><span>Rent collected</span><strong>{money(row.rent, row.currency)}</strong></p><p className="flex justify-between gap-2"><span>Expenses</span><strong>{money(row.expenses, row.currency)}</strong></p><p className="flex justify-between gap-2 text-teal-800"><span>Net rent</span><strong>{money(row.net, row.currency)}</strong></p></div>) : <Empty>No rent or expense entries in this period.</Empty>}</div></>}
          </Zone>
        </div>
        <Zone name="ULTRATIDY" subtitle="Cleaning business operations" href="/dashboard/ultratidy" icon={<Sparkles className="h-5 w-5" />}><div className="flex flex-wrap justify-between gap-4 items-center"><p className="text-sm text-slate-500 leading-relaxed max-w-md">Your existing cleaning operations are ready to access. Business performance measures have not yet been defined.</p><Link href="/dashboard/ultratidy" className={linkStyle}>Open operations <ChevronRight className="h-4 w-4" /></Link></div></Zone>
        <section className={`${panel} p-5 sm:p-6`} aria-label="CRM activity"><div className="flex justify-between gap-3 mb-4"><h2 className="font-heading font-semibold text-base">Recent leads</h2><Link href="/dashboard/leads" className={linkStyle}>View CRM <ArrowUpRight className="h-3.5 w-3.5" /></Link></div>{data.crm.error ? <Unavailable error={data.crm.error} /> : crm && <><div className="flex flex-wrap gap-x-5 gap-y-2 text-xs text-slate-500 mb-4"><p><strong className="text-slate-800">{number(crm.leads)}</strong> leads in period</p><p><strong className="text-slate-800">{number(crm.publishedPosts)}</strong> published posts</p><p><strong className="text-slate-800">{number(crm.dbaSalesCount)}</strong> DBA sales in period</p></div><div className="grid sm:grid-cols-2 gap-6 mb-5 pb-5 border-b border-slate-100"><Distribution title="Leads by status" rows={crm.leadsByStatus} /><Distribution title="Leads by business" rows={crm.leadsByBusiness} /></div>{crm.recentLeads.length ? <div className="divide-y divide-slate-100">{crm.recentLeads.map(row => <Link key={String(row.id)} href={`/dashboard/leads/${row.id}`} className="flex justify-between items-center gap-3 py-3 hover:text-teal-700"><div className="min-w-0"><p className="text-sm font-medium break-words">{String(row.name)}</p><p className="text-xs text-slate-500 mt-1 break-words">{label(row.business)} · {label(row.service)}</p></div><span className="text-[10px] rounded-full bg-slate-100 px-2.5 py-1 text-slate-600 shrink-0">{label(row.status)}</span></Link>)}</div> : <Empty>No leads yet. Customer inquiries will appear here.</Empty>}</>}</section>
      </div>
      <aside className="space-y-6 min-w-0" aria-label="Decisions and activity">
        <section className={`${panel} overflow-hidden`}><div className="bg-[#1B1464] text-white p-5"><p className="text-[10px] uppercase tracking-[0.16em] text-white/70">Primefield operations</p><div className="flex justify-between items-center gap-3 mt-2"><h2 className="font-heading text-lg font-semibold">Decision desk</h2><ClipboardList className="h-5 w-5 text-primary" /></div><p className="text-xs mt-2 text-white/70 leading-relaxed">Review requests, record your decision and follow through.</p></div><div className="p-5">{data.operations.error ? <Unavailable error={data.operations.error} /> : <>{pending.length ? <div className="space-y-4">{pending.slice(0, 5).map(row => <Link key={String(row.id)} href={`/dashboard/farm/operational-requests?request_id=${String(row.id)}`} className="block group"><div className="flex justify-between gap-2 text-[10px] text-slate-500"><span className="uppercase tracking-wider">{label(row.category)}</span><span className={row.status === "pending" ? "text-amber-700" : "text-teal-700"}>{row.status === "pending" ? "Decision needed" : "Follow-up"}</span></div><p className="text-sm font-medium mt-1 leading-relaxed line-clamp-3 break-words group-hover:text-teal-700">{String(row.description)}</p><p className="text-xs mt-2 break-words text-slate-600">Action taken: {row.action_taken?String(row.action_taken):"Not recorded"}</p><p className="text-[11px] text-slate-500 mt-1 break-all">Submitted by {String(row.requested_by??"Unknown")} · {String(row.created_at??row.request_date)}</p>{row.report_id&&<span className="text-[11px] mt-1 text-teal-700">Linked daily report</span>}</Link>)}</div> : <div className="py-3"><CircleCheck className="h-6 w-6 text-teal-600 mb-3" /><p className="text-sm font-medium">No outstanding requests</p><p className="text-xs text-slate-500 mt-1 leading-relaxed">New requests will appear here when the farm manager submits them.</p></div>}<Link className={`${linkStyle} mt-5`} href="/dashboard/farm/operational-requests">View all requests <ArrowUpRight className="h-3.5 w-3.5" /></Link></>}</div></section>
        <section className={`${panel} p-5`}><h2 className="font-heading text-sm font-semibold mb-4">Latest farm reports</h2>{data.operations.error ? <Unavailable error={data.operations.error} /> : data.operations.data?.recentReports.length ? <div className="space-y-4">{data.operations.data.recentReports.map(row => <Link key={String(row.id)} href={`/dashboard/farm/daily-reports?report_id=${String(row.id)}`} className="flex items-center justify-between gap-3 group"><div><p className="text-sm font-medium group-hover:text-teal-700">{String(row.report_date)}</p><p className="text-[11px] text-slate-500 mt-1">{row.reviewed_at ? "Reviewed" : "Awaiting review"}</p></div><ChevronRight className="h-4 w-4 text-slate-400" /></Link>)}</div> : <Empty>No submitted reports yet.</Empty>}<Link className={`${linkStyle} mt-4`} href="/dashboard/farm/daily-reports">Report history <ArrowUpRight className="h-3.5 w-3.5" /></Link></section>
        <section className={`${panel} p-5`}><h2 className="font-heading text-sm font-semibold mb-3">Quick actions</h2><div className="space-y-1">{[{href:"/dashboard/leads?new=true",title:"Add Lead",icon:Plus},{href:"/dashboard/blog/new",title:"New Blog Post",icon:Plus},{href:"/dashboard/appointments",title:"View Appointments",icon:CalendarDays},{href:"/dashboard/dba/products/new",title:"Add DBA Product",icon:Plus}].map(action => <Link key={action.href} href={action.href} className="flex min-h-11 gap-3 items-center py-3 text-xs font-medium hover:text-teal-700"><action.icon className="h-4 w-4 text-slate-400" />{action.title}<ChevronRight className="h-3.5 w-3.5 ml-auto text-slate-400" /></Link>)}</div>{crm && <p className="text-[11px] mt-3 pt-3 border-t border-slate-100 text-slate-500">{number(crm.pendingAppointments)} pending appointments</p>}</section>
      </aside></div></>}
    </div>
  </div>;
}
