import {createCipheriv,createDecipheriv,randomBytes,createHmac,timingSafeEqual,randomUUID} from "crypto";
import {createServerClient} from "@/lib/supabase/server";
export function socialConfig(){const key=process.env.CONTENT_TOKEN_ENCRYPTION_KEY;const redirect=process.env.INSTAGRAM_REDIRECT_URI;return {configured:!!(key&&Buffer.from(key,'base64').length===32&&process.env.INSTAGRAM_APP_ID&&process.env.INSTAGRAM_APP_SECRET&&redirect&&/^https:\/\//.test(redirect)&&/^v\d+\.\d+$/.test(process.env.INSTAGRAM_API_VERSION||'')),redirect,appId:process.env.INSTAGRAM_APP_ID,version:process.env.INSTAGRAM_API_VERSION}}
function key(){const value=Buffer.from(process.env.CONTENT_TOKEN_ENCRYPTION_KEY||'','base64');if(value.length!==32)throw Error('Social encryption is not configured');return value}
export function encryptSocialToken(token:string){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key(),iv),encrypted=Buffer.concat([cipher.update(token,'utf8'),cipher.final()]);return ['v1',iv.toString('base64'),cipher.getAuthTag().toString('base64'),encrypted.toString('base64')].join('.')}
export function decryptSocialToken(value:string){const [version,iv,tag,body]=value.split('.');if(version!=='v1'||!body)throw Error('Invalid stored token');const decipher=createDecipheriv('aes-256-gcm',key(),Buffer.from(iv,'base64'));decipher.setAuthTag(Buffer.from(tag,'base64'));return Buffer.concat([decipher.update(Buffer.from(body,'base64')),decipher.final()]).toString('utf8')}
export function socialState(actor:string,platform="instagram"){const payload=Buffer.from(JSON.stringify({actor,platform,nonce:randomBytes(24).toString('hex'),expires:Date.now()+600000})).toString('base64url');return payload+'.'+createHmac('sha256',key()).update(payload).digest('base64url')}
export function verifySocialState(state:string,actor:string,platform="instagram"){try{if(state.split(".").length!==2)return false;const [payload,signature]=state.split('.'),expected=createHmac('sha256',key()).update(payload).digest();const provided=Buffer.from(signature||'','base64url');if(expected.length!==provided.length||!timingSafeEqual(expected,provided))return false;const value=JSON.parse(Buffer.from(payload,'base64url').toString('utf8'));return value.actor===actor&&value.platform===platform&&value.expires>Date.now()}catch{return false}}
export async function officialFetch(url:string,init?:RequestInit){const response=await fetch(url,{...init,cache:'no-store',signal:AbortSignal.timeout(15000)});const json=await response.json();if(!response.ok||json.error)throw Error('The social provider did not authorize this request. Reconnect or enter metrics manually.');return json}
export async function socialWrite(actor:string,kind:string,payload:Record<string,unknown>,row?:Record<string,unknown>){const db=createServerClient();if(!db)throw Error('Database unavailable');const {data,error}=await db.rpc('content_write',{p_actor:actor,p_kind:kind,p_operation:row?'update':'create',p_payload:{...payload,...(row?{expected_revision:row.revision}:{})},p_id:row?.id||null,p_reason:row?'Official account authorization / synchronization':null,p_request_id:randomUUID()});if(error)throw error;return data as Record<string,unknown>}
export async function integrationRow(platform='instagram'){const db=createServerClient();if(!db)throw Error('Database unavailable');const {data,error}=await db.from('content_social_integrations').select('*').eq('platform',platform).maybeSingle();if(error)throw error;return data as Record<string,unknown>|null}


