import {NextRequest,NextResponse} from "next/server";
import {requireContentManager} from "@/lib/auth";
import {createServerClient} from "@/lib/supabase/server";
import {farmDateToday} from "@/lib/farm-products";
import {contentError} from "@/lib/content";
import {socialState,verifySocialState,encryptSocialToken,decryptSocialToken,integrationRow,socialWrite} from "@/lib/content-social";
export type SocialPlatform="facebook"|"tiktok";
type Row=Record<string,unknown>;
type TikTokToken={access_token:string;refresh_token:string;refresh_expires_at:string;open_id:string};
function redirectUri(value:string|undefined){try{const u=new URL(value||'');return u.protocol==='https:'&&!u.search&&!u.hash&&u.href.length<512}catch{return false}}
export function platformConfig(platform:SocialPlatform){const key=process.env.CONTENT_TOKEN_ENCRYPTION_KEY,encryption=!!key&&Buffer.from(key,'base64').length===32;if(platform==='facebook'){const redirect=process.env.FACEBOOK_REDIRECT_URI,appId=process.env.FACEBOOK_APP_ID,secret=process.env.FACEBOOK_APP_SECRET,version=process.env.FACEBOOK_API_VERSION,pageId=process.env.FACEBOOK_PAGE_ID;return {configured:!!(encryption&&appId&&secret&&redirectUri(redirect)&&/^v\d+\.\d+$/.test(version||'')&&/^\d+$/.test(pageId||'')),redirect,appId,secret,version,pageId}}const redirect=process.env.TIKTOK_REDIRECT_URI,appId=process.env.TIKTOK_CLIENT_KEY,secret=process.env.TIKTOK_CLIENT_SECRET;return {configured:!!(encryption&&appId&&secret&&redirectUri(redirect)),redirect,appId,secret,version:undefined,pageId:undefined}}
export async function platformFetch(platform:SocialPlatform,url:string,init?:RequestInit){const response=await fetch(url,{...init,cache:'no-store',signal:AbortSignal.timeout(15000)});const json=await response.json();const error=platform==='tiktok'?(json.error&&(typeof json.error==='string'||json.error.code!=='ok')):json.error;if(!response.ok||error)throw Error('Official account access failed. Reauthorize or enter measured performance manually.');return json}
function expiry(seconds:unknown){if(typeof seconds!=='number'||!Number.isFinite(seconds)||seconds<=0||seconds>366*86400)throw Error('Invalid token expiry');return new Date(Date.now()+seconds*1000).toISOString()}
function tiktokBundle(token:Row):TikTokToken{if(typeof token.access_token!=='string'||!token.access_token||typeof token.refresh_token!=='string'||!token.refresh_token||typeof token.open_id!=='string'||!token.open_id||typeof token.scope!=='string'||!token.scope.split(',').includes('user.info.stats'))throw Error('Required TikTok statistics permission was not granted');return {access_token:token.access_token,refresh_token:token.refresh_token,refresh_expires_at:expiry(token.refresh_expires_in),open_id:token.open_id}}
async function persistToken(actor:string,integration:Row,secret:string,expiresAt:string){const db=createServerClient();if(!db)throw Error('Database unavailable');const {data:meta,error}=await db.rpc('content_social_token_metadata',{p_actor:actor,p_integration_id:integration.id});if(error)throw error;await socialWrite(actor,'token',{integration_id:integration.id,ciphertext:encryptSocialToken(secret),expires_at:expiresAt},meta||undefined)}
function cookieOptions(platform:SocialPlatform){return {httpOnly:true,secure:true,sameSite:'lax' as const,maxAge:600,path:`/api/content/social/${platform}`}}
async function authorize(platform:SocialPlatform,actor:string){const config=platformConfig(platform);if(!config.configured)return NextResponse.json({error:`${platform==='facebook'?'Facebook Page':'TikTok'} developer configuration is required. Manual entry remains available.`},{status:503});const state=socialState(actor,platform),url=new URL(platform==='facebook'?`https://www.facebook.com/${config.version}/dialog/oauth`:'https://www.tiktok.com/v2/auth/authorize/');url.search=new URLSearchParams({[platform==='facebook'?'client_id':'client_key']:config.appId!,redirect_uri:config.redirect!,response_type:'code',scope:platform==='facebook'?'pages_show_list,pages_read_engagement':'user.info.basic,user.info.stats',state}).toString();const response=NextResponse.redirect(url);response.cookies.set(`content_${platform}_state`,state,cookieOptions(platform));return response}
async function callback(request:NextRequest,platform:SocialPlatform,actor:string){let connected:Row|undefined;try{const config=platformConfig(platform);if(!config.configured)return NextResponse.json({error:'Developer configuration is required.'},{status:503});const state=request.nextUrl.searchParams.get('state')||'';if(state!==request.cookies.get(`content_${platform}_state`)?.value||!verifySocialState(state,actor,platform))return NextResponse.json({error:'Authorization expired or invalid. Start again.'},{status:400});const code=request.nextUrl.searchParams.get('code');if(!code||request.nextUrl.searchParams.has('error'))return NextResponse.json({error:'Account authorization was not granted.'},{status:400});let accountId:string,accountName:string,secret:string,expiresAt:string;
 if(platform==='facebook'){
  const endpoint=`https://graph.facebook.com/${config.version}/oauth/access_token`,shortUrl=new URL(endpoint);shortUrl.search=new URLSearchParams({client_id:config.appId!,client_secret:config.secret!,redirect_uri:config.redirect!,code}).toString();const short=await platformFetch(platform,shortUrl.toString());if(typeof short.access_token!=='string')throw Error('Token unavailable');const longUrl=new URL(endpoint);longUrl.search=new URLSearchParams({grant_type:'fb_exchange_token',client_id:config.appId!,client_secret:config.secret!,fb_exchange_token:short.access_token}).toString();const long=await platformFetch(platform,longUrl.toString());if(typeof long.access_token!=='string')throw Error('Token unavailable');expiresAt=expiry(long.expires_in);let next=`https://graph.facebook.com/${config.version}/me/accounts?fields=id,name,access_token&limit=100`,selected:Row|undefined;
  for(let page=0;next&&page<100;page++){const result=await platformFetch(platform,next,{headers:{Authorization:`Bearer ${long.access_token}`}});if(!Array.isArray(result.data))throw Error('Pages unavailable');selected=result.data.find((row:Row)=>String(row.id)===config.pageId);if(selected)break;next=typeof result.paging?.next==='string'?result.paging.next:'';if(next){const allowed=new URL(next);if(allowed.protocol!=='https:'||allowed.hostname!=='graph.facebook.com')throw Error('Invalid provider pagination')}}
  if(!selected||typeof selected.access_token!=='string'||!selected.access_token)throw Error('The configured Page was not authorized');accountId=String(selected.id);accountName=String(selected.name||accountId);secret=selected.access_token;
 }else{
  const body=new URLSearchParams({client_key:config.appId!,client_secret:config.secret!,grant_type:'authorization_code',redirect_uri:config.redirect!,code});const token=await platformFetch(platform,'https://open.tiktokapis.com/v2/oauth/token/',{method:'POST',body,headers:{'Content-Type':'application/x-www-form-urlencoded'}});const bundle=tiktokBundle(token);expiresAt=expiry(token.expires_in);const profile=await platformFetch(platform,'https://open.tiktokapis.com/v2/user/info/?fields=open_id,display_name,follower_count',{headers:{Authorization:`Bearer ${bundle.access_token}`}});if(profile.data?.user?.open_id!==bundle.open_id)throw Error('Account mismatch');accountId=bundle.open_id;accountName=String(profile.data.user.display_name||accountId);secret=JSON.stringify(bundle);
 }
 connected=await socialWrite(actor,'integration',{platform,account_id:accountId,account_name:accountName,status:'connected',last_error:null},await integrationRow(platform)||undefined);await persistToken(actor,connected,secret,expiresAt);const response=NextResponse.redirect(new URL(`/content/integrations?connected=${platform}`,request.url));response.cookies.set(`content_${platform}_state`,'',{...cookieOptions(platform),maxAge:0});return response;
 }catch(error){if(connected){try{await socialWrite(actor,'integration',{status:'error',last_error:'Authorization could not be completed. Please reconnect.'},connected)}catch{}}return contentError(error)}}
async function sync(platform:SocialPlatform,actor:string){const config=platformConfig(platform);if(!config.configured)return NextResponse.json({error:'Official account access is not configured. Enter performance manually.'},{status:503});const integration=await integrationRow(platform);if(!integration||integration.status!=='connected')return NextResponse.json({error:'Authorize the account first.'},{status:409});const db=createServerClient();if(!db)throw Error('Database unavailable');const {data:stored,error}=await db.rpc('content_social_token_read',{p_actor:actor,p_integration_id:integration.id});if(error)throw error;if(!stored)return NextResponse.json({error:'Authorization expired. Reauthorize the account.'},{status:409});let secret=decryptSocialToken(stored.ciphertext),followers:unknown;
 if(platform==='facebook'){const profile=await platformFetch(platform,`https://graph.facebook.com/${config.version}/${encodeURIComponent(String(integration.account_id))}?fields=followers_count`,{headers:{Authorization:`Bearer ${secret}`}});followers=profile.followers_count;
 }else{let bundle=JSON.parse(secret) as TikTokToken;if(bundle.open_id!==integration.account_id)throw Error('Account mismatch');if(new Date(stored.expires_at).getTime()-Date.now()<1800000){if(new Date(bundle.refresh_expires_at).getTime()<=Date.now())return NextResponse.json({error:'Refresh authorization expired. Reauthorize TikTok.'},{status:409});const body=new URLSearchParams({client_key:config.appId!,client_secret:config.secret!,grant_type:'refresh_token',refresh_token:bundle.refresh_token});const refreshed=await platformFetch(platform,'https://open.tiktokapis.com/v2/oauth/token/',{method:'POST',body,headers:{'Content-Type':'application/x-www-form-urlencoded'}});const replacement=tiktokBundle(refreshed);if(replacement.open_id!==integration.account_id)throw Error('Refresh account mismatch');bundle=replacement;secret=JSON.stringify(bundle);await persistToken(actor,integration,secret,expiry(refreshed.expires_in))}const profile=await platformFetch(platform,'https://open.tiktokapis.com/v2/user/info/?fields=open_id,follower_count',{headers:{Authorization:`Bearer ${bundle.access_token}`}});if(profile.data?.user?.open_id!==integration.account_id)throw Error('Account mismatch');followers=profile.data.user.follower_count}
 if(typeof followers!=='number'||!Number.isSafeInteger(followers)||followers<0)throw Error('Follower metric unavailable');const date=farmDateToday(),{data:existing,error:snapshotError}=await db.from('content_performance').select('*').eq('platform',platform).eq('account_id',String(integration.account_id)).is('content_id',null).eq('metric_date',date).maybeSingle();if(snapshotError)throw snapshotError;if(existing?.source==='manual')return NextResponse.json({error:'A manual snapshot already exists for this account/date. Preserve it or apply an audited manual correction.'},{status:409});const data=await socialWrite(actor,'performance',{platform,account_id:integration.account_id,metric_date:date,followers,source:'official',notes:`Official ${platform==='facebook'?'Facebook Page':'TikTok'} follower snapshot. Other metrics are unavailable in this import.`},existing||undefined);await socialWrite(actor,'integration',{last_sync_at:new Date().toISOString(),last_error:null},integration);return NextResponse.json({data})}
export async function platformAction(request:NextRequest,platform:string,action:string,method:'GET'|'POST'){try{const actor=await requireContentManager();if(actor.role!=='admin')return NextResponse.json({error:'CEO account authorization required'},{status:403});if(!['facebook','tiktok'].includes(platform))return NextResponse.json({error:'Not found'},{status:404});const selected=platform as SocialPlatform;if(method==='GET'&&action==='authorize')return authorize(selected,actor.id);if(method==='GET'&&action==='callback')return callback(request,selected,actor.id);if(method==='POST'&&action==='sync')return await sync(selected,actor.id);if(method==='POST'&&action==='disconnect'){const row=await integrationRow(selected);return NextResponse.json({data:row?await socialWrite(actor.id,'integration',{status:'disconnected',last_error:null},row):null})}return NextResponse.json({error:'Not found'},{status:404})}catch(error){return contentError(error)}}
