import { z } from "zod";
import { NextResponse } from "next/server";
import { requireContentManager } from "@/lib/auth";
import { createServerClient } from "@/lib/supabase/server";
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const d=new Date(`${v}T00:00:00Z`);return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===v},"Use a real calendar date");
const timestamp=z.string().datetime({offset:true}).nullable().optional();
const platform=z.enum(["instagram","facebook","tiktok"]);
const notes=z.string().max(3000).nullable().optional();
const link=z.string().url().refine(v=>/^https?:\/\//.test(v),"Use an http or https URL").nullable().optional();
const uuid=z.string().uuid().nullable().optional();
const count=z.number().int().min(0).max(Number.MAX_SAFE_INTEGER).nullable().optional();
export const contentSchemas={
 records:z.object({title:z.string().trim().min(1).max(300),platform,content_type:z.string().trim().min(1).max(100),status:z.enum(["draft","scheduled","published","archived"]),published_at:timestamp,scheduled_at:timestamp,url:link,notes}).strict().refine(v=>v.status!=="published"||!!v.published_at,"Publication date required").refine(v=>v.status!=="scheduled"||!!v.scheduled_at,"Schedule date required"),
 performance:z.object({content_id:uuid,platform,account_id:z.string().max(200).optional(),metric_date:date,followers:count,reach:count,impressions:count,engagements:count,source:z.literal("manual").optional(),notes}).strict().refine(v=>[v.followers,v.reach,v.impressions,v.engagements].some(x=>x!=null),"Enter at least one measured metric"),
 leads:z.object({content_id:uuid,platform,name:z.string().trim().min(1).max(200),contact:z.string().max(500).nullable().optional(),status:z.enum(["new","contacted","converted","closed"]),lead_date:date,notes}).strict(),
 sales:z.object({content_id:uuid,lead_id:uuid,sale_type:z.enum(["mentorship","affiliate"]),amount:z.number().positive().max(99999999999999.99),currency:z.string().regex(/^[A-Z]{3}$/),sale_date:date,customer_name:z.string().max(200).nullable().optional(),notes}).strict()
};
export const contentTables={records:"content_records",performance:"content_performance",leads:"content_leads",sales:"content_sales",integrations:"content_social_integrations",history:"content_audit"} as const;
export type ContentKind=keyof typeof contentSchemas;
export function contentError(error:unknown){if(error instanceof z.ZodError)return NextResponse.json({error:error.issues[0]?.message||"Invalid values"},{status:400});const e=error as {message?:string;code?:string};if(e?.code==="42501"||e?.message?.startsWith("Unauthorized"))return NextResponse.json({error:"Content access required"},{status:403});if(["40001","23505"].includes(e?.code||""))return NextResponse.json({error:"Record changed or already exists. Refresh before saving."},{status:409});if(e?.code==="P0002")return NextResponse.json({error:"Record not found"},{status:404});if(e?.code==="23514"&&e.message?.startsWith("Content platform cannot change while leads or performance records are linked."))return NextResponse.json({error:"Platform is locked because leads or performance are linked. Create a separate record for the other platform."},{status:400});if(["22023","23514","23503","22P02"].includes(e?.code||""))return NextResponse.json({error:"Check the values and linked records before saving."},{status:400});return NextResponse.json({error:"Content data is unavailable. Please try again."},{status:503})}
export async function contentList(request:Request,kind:string){try{await requireContentManager();if(!(Object.prototype.hasOwnProperty.call(contentTables,kind)))return NextResponse.json({error:"Not found"},{status:404});const db=createServerClient();if(!db)throw Error("Database unavailable");const page=Number(new URL(request.url).searchParams.get("page")||"0");if(!Number.isInteger(page)||page<0)return NextResponse.json({error:"Invalid page"},{status:400});const table=contentTables[kind as keyof typeof contentTables];const {data,error}=await db.from(table).select("*").order(kind==="history"?"happened_at":"created_at",{ascending:false}).order("id",{ascending:false}).range(page*100,page*100+99);if(error)throw error;return NextResponse.json({data:data||[],page,has_more:data?.length===100})}catch(error){return contentError(error)}}
export async function contentSave(request:Request,kind:string,update=false){try{const actor=await requireContentManager();if(!(Object.prototype.hasOwnProperty.call(contentSchemas,kind)))return NextResponse.json({error:"Use the authorization workflow for integrations"},{status:405});let body:unknown;try{body=await request.json()}catch{return NextResponse.json({error:"Invalid JSON"},{status:400})}const envelope=z.object({request_id:z.string().uuid(),data:z.record(z.string(),z.unknown()),...(update?{id:z.string().uuid(),expected_revision:z.number().int().min(0),reason:z.string().trim().min(1).max(2000)}:{})}).strict().parse(body);const values=contentSchemas[kind as ContentKind].parse(envelope.data);const db=createServerClient();if(!db)throw Error("Database unavailable");const details=envelope as typeof envelope & {id?:string;expected_revision?:number;reason?:string};const {data,error}=await db.rpc("content_write",{p_actor:actor.id,p_kind:({records:"record",performance:"performance",leads:"lead",sales:"sale"} as const)[kind as ContentKind],p_operation:update?"update":"create",p_payload:{...values,...(update?{expected_revision:details.expected_revision}:{})},p_id:details.id||null,p_reason:details.reason||null,p_request_id:envelope.request_id});if(error)throw error;return NextResponse.json({data},{status:update?200:201})}catch(error){return contentError(error)}}
