import {NextRequest,NextResponse} from "next/server";
import {requireContentManager} from "@/lib/auth";
import {socialConfig,verifySocialState,officialFetch,encryptSocialToken,integrationRow,socialWrite} from "@/lib/content-social";
import {contentError} from "@/lib/content";
export const dynamic="force-dynamic";
export async function GET(request:NextRequest){let connected:Record<string,unknown>|undefined;let actorId='';try{const actor=await requireContentManager();actorId=actor.id;if(actor.role!=='admin')return NextResponse.json({error:'CEO authorization required'},{status:403});const config=socialConfig();if(!config.configured)throw Error('Configuration missing');const state=request.nextUrl.searchParams.get('state')||'';if(state!==request.cookies.get('content_instagram_state')?.value||!verifySocialState(state,actor.id))return NextResponse.json({error:'Authorization expired or invalid. Start again.'},{status:400});const code=request.nextUrl.searchParams.get('code');if(!code||request.nextUrl.searchParams.has('error'))return NextResponse.json({error:'Account authorization was not granted.'},{status:400});const body=new URLSearchParams({client_id:config.appId!,client_secret:process.env.INSTAGRAM_APP_SECRET!,grant_type:'authorization_code',redirect_uri:config.redirect!,code});const short=await officialFetch('https://api.instagram.com/oauth/access_token',{method:'POST',body});if(typeof short.access_token!=='string')throw Error('No token');const exchange=new URL('https://graph.instagram.com/access_token');exchange.search=new URLSearchParams({grant_type:'ig_exchange_token',client_secret:process.env.INSTAGRAM_APP_SECRET!,access_token:short.access_token}).toString();const token=await officialFetch(exchange.toString());if(typeof token.access_token!=='string'||(!Number.isFinite(token.expires_in)||token.expires_in<=0))throw Error('No long lived token');const profile=await officialFetch(`https://graph.instagram.com/${config.version}/me?fields=user_id,username`,{headers:{Authorization:`Bearer ${token.access_token}`}});const id=String(profile.user_id||profile.id||'');if(!/^\d+$/.test(id))throw Error('Invalid account');connected=await socialWrite(actor.id,'integration',{platform:'instagram',account_id:id,account_name:String(profile.username||id),status:'connected',last_error:null},await integrationRow()||undefined);const expires=new Date(Date.now()+token.expires_in*1000).toISOString();const db=(await import('@/lib/supabase/server')).createServerClient();if(!db)throw Error('Database unavailable');const {data:existing,error}=await db.rpc('content_social_token_metadata',{p_actor:actor.id,p_integration_id:connected.id});if(error)throw error;
 // Reauthorization invalidates the old token; retrieve only its non-secret revision metadata through a guarded RPC.
 await socialWrite(actor.id,'token',{integration_id:connected.id,ciphertext:encryptSocialToken(token.access_token),expires_at:expires},existing||undefined);
 const response=NextResponse.redirect(new URL('/content/integrations?connected=instagram',request.url));response.cookies.set('content_instagram_state','',{httpOnly:true,secure:true,sameSite:'lax',maxAge:0,path:'/api/content/social/instagram'});return response}catch(e){if(connected&&actorId){try{await socialWrite(actorId,'integration',{status:'error',last_error:'Authorization could not be completed. Please reconnect.'},connected)}catch{}}return contentError(e)}}
